name: measure_size_builder
description: "Simplest way to get dynamic size of widget"
version: 1.0.3
homepage: https://github.com/Xim-ya/measure_size_builder

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

